output_folder: ./recordings
segment_duration: 60  
log_file: record_rtsp.log 
cameras:
  - name: Camera1
    rtsp_url: rtsp://admin:password@192.168.1.10:554/stream
  - name: Camera2
    rtsp_url: rtsp://admin:password@192.168.1.11:554/stream
  - name: Camera3
    rtsp_url: rtsp://admin:password@192.168.1.12:554/stream
