segment_duration: 30
log_file: ./logs/record_rtsp.log
output_folder: ./recordings
cameras:
  - name: Camera1
    rtsp_url: rtsp://camera.example/stream1  
  - name: Camera2
    rtsp_url: rtsp://camera.example/stream2 
  - name: Camera3
    rtsp_url: rtsp://camera.example/stream3
web_server:
  enabled: true
  port: 8080
  user: admin
  password_hash: 5487cf596c53bf12e05cec7d9e2b719478cba212eb9e146e927900b48825f872 #sha256 hash from passphrase. Default pass: demopassword
  html_page: index.html
