segment_duration: 30
log_file: ./logs/record_rtsp.log
cameras:
  - name: Camera1
    rtsp_url: rtsp://cam.stream/1
    output_folder: ./recordings/camera1  
  - name: Camera2
    rtsp_url: rtsp://cam.stream/2
    output_folder: ./recordings/camera2  
